package io.github.jimbozoomer.jugcraft.tower;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import io.github.jimbozoomer.jugcraft.Jugcraft;
import io.github.jimbozoomer.jugcraft.drone.DroneSize;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.zip.GZIPInputStream;
import net.minecraft.commands.arguments.blocks.BlockStateParser;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;

/**
 * The Drone Tower's design, tier by tier, as generated by tools/drone_tower.py into
 * {@code data/jugcraft/drone_tower/tower.json.gz}: for each tier the blocks to place and clear (relative to the
 * Tower Core, which sits in the middle of its 15x15 plinth), its hangar docks, supply pickups, drone capacity
 * and module cost. Read once from the mod jar.
 *
 * <p>The blocks of tiers 2 to 9 are grouped into {@link Tile}s of up to 3x3 blocks in one layer: a drone
 * delivers one tile per stop (each tile is still placed block by block from the modules paid for the
 * upgrade).
 */
public final class TowerData {
	public static final int TIERS = 9;
	/** Edge of a build tile (blocks per side). */
	public static final int TILE = 4;

	/**
	 * A hangar: its floor centre, size class, the point outside its bay a drone flies out to, and its bay door
	 * ({x0, z0, x1, z1, bottom y, height, out x, out z}: the opening's end cells and which way is outside; or null).
	 */
	public record Dock(int tier, DroneSize size, double x, double y, double z, double exitX, double exitZ, int @org.jspecify.annotations.Nullable [] door) {
	}

	/** A supply pickup on the tower: the north-west plate of its 3x3, and the plates' level. */
	public record Pickup(int tier, int x, int y, int z) {
	}

	/** A ground pad (north-west corner) and where its drones fly out once the hangar deck covers it. */
	public record Pad(int x, int z, double exitX, double exitZ) {
	}

	/**
	 * Up to 4x4 blocks of one layer, delivered together; (x, y, z) is its first block (or first cell to clear);
	 * {@code blocks} index {@link Tier#place}, {@code air} index {@link Tier#air}: cells of the same layer and
	 * cell that must be emptied first (stray blocks inside the tower's rooms, hangars and the space under the deck).
	 */
	public record Tile(int x, int y, int z, int[] blocks, int[] air) {
	}

	public static final class Tier {
		public final int number;
		public final String name;
		public final int top;
		/** {dx, dy, dz, palette} per block, bottom layer first. */
		public final int[][] place;
		/** {dx, dy, dz} of blocks the tier removes (a lower tier's antenna). */
		public final int[][] clear;
		/** {dx, dy, dz} of cells inside the tier that must be empty: whatever stray block is there gets cleared. */
		public final int[][] air;
		public final List<Dock> docks;
		public final List<Pickup> pickups;
		public final int capacity;
		public final Map<String, Integer> modules;
		public final List<Tile> tiles;

		Tier(int number, String name, int top, int[][] place, int[][] clear, int[][] air, List<Dock> docks, List<Pickup> pickups,
				int capacity, Map<String, Integer> modules) {
			this.number = number;
			this.name = name;
			this.top = top;
			this.place = place;
			this.clear = clear;
			this.air = air;
			this.docks = docks;
			this.pickups = pickups;
			this.capacity = capacity;
			this.modules = modules;
			this.tiles = tiles(place, air);
		}
	}

	private static TowerData instance;

	public final List<BlockState> palette;
	public final List<Tier> tiers;
	public final List<Pad> pads;
	public final int plinth;
	/** Where tier 1 puts the Drone Depot Terminal, relative to the core. */
	public final int[] terminal;

	private TowerData(List<BlockState> palette, List<Tier> tiers, List<Pad> pads, int plinth, int[] terminal) {
		this.palette = palette;
		this.tiers = tiers;
		this.pads = pads;
		this.plinth = plinth;
		this.terminal = terminal;
	}

	public static synchronized TowerData get() {
		if (instance == null) {
			instance = load();
		}
		return instance;
	}

	/** Tier {@code number} (1 to 9). */
	public Tier tier(int number) {
		return tiers.get(number - 1);
	}

	/** Drones a tower of {@code tier} holds (0 before tier 1). */
	public int capacity(int tier) {
		return tier <= 0 ? 0 : tier(Math.min(TIERS, tier)).capacity;
	}

	public BlockState state(int paletteIndex) {
		return palette.get(paletteIndex);
	}

	private static TowerData load() {
		String path = "/data/jugcraft/drone_tower/tower.json.gz";
		try (InputStream raw = TowerData.class.getResourceAsStream(path)) {
			if (raw == null) {
				throw new IllegalStateException("missing " + path);
			}
			JsonObject root = JsonParser.parseReader(new InputStreamReader(new GZIPInputStream(raw), StandardCharsets.UTF_8)).getAsJsonObject();
			List<BlockState> palette = new ArrayList<>();
			for (JsonElement entry : root.getAsJsonArray("palette")) {
				palette.add(parse(entry.getAsString()));
			}
			List<Tier> tiers = new ArrayList<>();
			for (JsonElement element : root.getAsJsonArray("tiers")) {
				JsonObject t = element.getAsJsonObject();
				List<Dock> docks = new ArrayList<>();
				for (JsonElement d : t.getAsJsonArray("docks")) {
					JsonObject o = d.getAsJsonObject();
					docks.add(new Dock(o.get("tier").getAsInt(), DroneSize.valueOf(o.get("size").getAsString().toUpperCase(Locale.ROOT)),
							o.get("x").getAsDouble(), o.get("y").getAsDouble(), o.get("z").getAsDouble(), o.get("ex").getAsDouble(),
							o.get("ez").getAsDouble(), o.has("door") ? ints1(o.getAsJsonArray("door")) : null));
				}
				List<Pickup> pickups = new ArrayList<>();
				for (JsonElement p : t.getAsJsonArray("pickups")) {
					JsonObject o = p.getAsJsonObject();
					pickups.add(new Pickup(o.get("tier").getAsInt(), o.get("x").getAsInt(), o.get("y").getAsInt(), o.get("z").getAsInt()));
				}
				Map<String, Integer> modules = new LinkedHashMap<>();
				for (Map.Entry<String, JsonElement> m : t.getAsJsonObject("modules").entrySet()) {
					modules.put(m.getKey(), m.getValue().getAsInt());
				}
				tiers.add(new Tier(t.get("tier").getAsInt(), t.get("name").getAsString(), t.get("top").getAsInt(), ints(t.getAsJsonArray("place")),
						ints(t.getAsJsonArray("clear")), t.has("air") ? ints(t.getAsJsonArray("air")) : new int[0][], docks, pickups, t.get("capacity").getAsInt(), modules));
			}
			List<Pad> pads = new ArrayList<>();
			for (JsonElement p : root.getAsJsonArray("pads")) {
				JsonObject o = p.getAsJsonObject();
				pads.add(new Pad(o.get("x").getAsInt(), o.get("z").getAsInt(), o.get("ex").getAsDouble(), o.get("ez").getAsDouble()));
			}
			JsonArray terminal = root.getAsJsonArray("terminal");
			return new TowerData(palette, tiers, pads, root.get("plinth").getAsInt(),
					new int[] {terminal.get(0).getAsInt(), terminal.get(1).getAsInt(), terminal.get(2).getAsInt()});
		} catch (Exception e) {
			Jugcraft.LOGGER.error("Could not read the Drone Tower data", e);
			throw new IllegalStateException("Drone Tower data unreadable", e);
		}
	}

	private static BlockState parse(String state) {
		try {
			return BlockStateParser.parseForBlock(BuiltInRegistries.BLOCK, state, false).blockState();
		} catch (Exception e) {
			Jugcraft.LOGGER.error("Drone Tower data: unknown block state {}", state);
			return Blocks.AIR.defaultBlockState();
		}
	}

	private static int[][] ints(JsonArray array) {
		int[][] out = new int[array.size()][];
		for (int i = 0; i < out.length; i++) {
			JsonArray row = array.get(i).getAsJsonArray();
			out[i] = new int[row.size()];
			for (int j = 0; j < out[i].length; j++) {
				out[i][j] = row.get(j).getAsInt();
			}
		}
		return out;
	}

	private static long tileKey(int[] b) {
		return b[1] * 1_000_000L + (Math.floorDiv(b[0], TILE) + 500) * 1000L + (Math.floorDiv(b[2], TILE) + 500);
	}

	/**
	 * Groups a tier's blocks and cells to clear into tiles of up to {@link #TILE}x{@link #TILE} in one layer,
	 * bottom layers first. A cell to clear with no block in its tile gets a clear-only tile.
	 */
	private static List<Tile> tiles(int[][] place, int[][] air) {
		Map<Long, List<Integer>> groups = new LinkedHashMap<>();
		Map<Long, List<Integer>> clears = new LinkedHashMap<>();
		for (int i = 0; i < place.length; i++) {
			groups.computeIfAbsent(tileKey(place[i]), k -> new ArrayList<>()).add(i);
		}
		for (int i = 0; i < air.length; i++) {
			long key = tileKey(air[i]);
			groups.computeIfAbsent(key, k -> new ArrayList<>());
			clears.computeIfAbsent(key, k -> new ArrayList<>()).add(i);
		}
		List<Tile> tiles = new ArrayList<>();
		for (Map.Entry<Long, List<Integer>> group : groups.entrySet()) {
			int[] blocks = group.getValue().stream().mapToInt(Integer::intValue).toArray();
			int[] cells = clears.getOrDefault(group.getKey(), List.of()).stream().mapToInt(Integer::intValue).toArray();
			int[] first = blocks.length > 0 ? place[blocks[0]] : air[cells[0]];
			tiles.add(new Tile(first[0], first[1], first[2], blocks, cells));
		}
		tiles.sort((a, b) -> Integer.compare(a.y(), b.y()));
		return tiles;
	}

	private static int[] ints1(JsonArray array) {
		int[] out = new int[array.size()];
		for (int i = 0; i < out.length; i++) {
			out[i] = array.get(i).getAsInt();
		}
		return out;
	}
}
