package io.github.jimbozoomer.jugcraft.guide;

import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.Level;

/**
 * The Engineer's Handbook: right-click to read the in-game guide (client/HandbookScreen). The book is
 * purely client-side reading; its content comes from assets/jugcraft/handbook/, generated by tools/handbook.py.
 */
public class EngineersHandbookItem extends Item {
	/** Opens the handbook screen. Set by the client entrypoint; does nothing on a dedicated server. */
	public static Runnable openScreen = () -> {
	};

	public EngineersHandbookItem(Properties properties) {
		super(properties);
	}

	@Override
	public InteractionResult use(Level level, Player player, InteractionHand hand) {
		if (level.isClientSide()) {
			openScreen.run();
		}
		return InteractionResult.SUCCESS;
	}
}
