package io.github.jimbozoomer.jugcraft.client;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import io.github.jimbozoomer.jugcraft.Jugcraft;
import java.io.Reader;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.client.input.KeyEvent;
import net.minecraft.client.input.MouseButtonEvent;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.server.packs.resources.Resource;
import net.minecraft.util.FormattedCharSequence;
import net.minecraft.world.item.ItemStack;

/**
 * The Engineer's Handbook screen (reorganised in batch 23). The book sizes itself to the window. On the left, a
 * contents list of every chapter; the open chapter unfolds to show its pages, and the list scrolls when it is longer
 * than the book. On the right, the page: its title, then text, a crafting grid, machine recipes or a chain of
 * progression steps, scrolling when it is longer than the page. Arrows (buttons or keys) turn pages; the mouse wheel
 * scrolls whichever side it is over. Content: assets/jugcraft/handbook/en_us.json, generated by tools/handbook.py.
 * Reading only; nothing is sent to the server.
 */
public class HandbookScreen extends Screen {
	private static final Identifier CONTENT = Jugcraft.id("handbook/en_us.json");
	private static final int MIN_WIDTH = 300;
	private static final int MAX_WIDTH = 440;
	private static final int MIN_HEIGHT = 170;
	private static final int MAX_HEIGHT = 260;
	private static final int SIDE_WIDTH = 112;
	/** Heights of a chapter row and a page row in the contents list. */
	private static final int CHAPTER_ROW = 13;
	private static final int PAGE_ROW = 11;
	/** Space at the bottom of the page for the page buttons and counter. */
	private static final int FOOTER = 20;
	private static final int SCROLL_STEP = 12;
	/**
	 * Progression steps: a card's narrowest and widest width (cards share out the page width between them), its height
	 * and the gap (with an arrow) between cards.
	 */
	private static final int STEP_MIN_WIDTH = 56;
	private static final int STEP_MAX_WIDTH = 72;
	private static final int STEP_HEIGHT = 50;
	private static final int STEP_GAP = 8;

	// GLFW key codes.
	private static final int KEY_RIGHT = 262;
	private static final int KEY_LEFT = 263;
	private static final int KEY_DOWN = 264;
	private static final int KEY_UP = 265;
	private static final int KEY_PAGE_UP = 266;
	private static final int KEY_PAGE_DOWN = 267;

	private static final int BRASS = 0xFFB08A3A;
	private static final int BRASS_DARK = 0xFF6E5220;
	private static final int LEATHER = 0xFF4A2A18;
	private static final int LEATHER_DARK = 0xFF35190C;
	private static final int PAPER = 0xFFF1E6CB;
	private static final int PAPER_SHADE = 0xFFE2D2AE;
	private static final int INK = 0xFF3A2A1A;
	private static final int INK_LIGHT = 0xFF7A6040;
	private static final int SLOT = 0xFFD6C49C;
	private static final int TAB_TEXT = 0xFFF1E0B8;
	private static final int TAB_DIM = 0xFFB8A27A;
	private static final int TAB_SELECTED = 0xFF7A4A24;
	private static final int TAB_HOVER = 0xFF5E3820;

	private final List<JsonObject> chapters = new ArrayList<>();
	private int chapter;
	private int page;
	private int left;
	private int top;
	private int bookWidth;
	private int bookHeight;
	private int sideScroll;
	private int pageScroll;
	/** Height of the open page's scrolling body, measured as it is drawn. */
	private int pageHeight;
	private Button previous;
	private Button next;

	/** One row of the contents list: a chapter, or (page >= 0) a page of the open chapter. */
	private record Row(int chapter, int page, int y, int height) {
	}

	public HandbookScreen() {
		this(0, 0);
	}

	public HandbookScreen(int chapter, int page) {
		super(Component.translatable("item.jugcraft.engineers_handbook"));
		this.chapter = chapter;
		this.page = page;
		load();
	}

	private void load() {
		Optional<Resource> resource = Minecraft.getInstance().getResourceManager().getResource(CONTENT);
		if (resource.isEmpty()) {
			return;
		}
		try (Reader reader = resource.get().openAsReader()) {
			for (JsonElement element : JsonParser.parseReader(reader).getAsJsonObject().getAsJsonArray("chapters")) {
				chapters.add(element.getAsJsonObject());
			}
		} catch (Exception e) {
			Jugcraft.LOGGER.warn("Could not read the Engineer's Handbook", e);
		}
		chapter = Math.max(0, Math.min(chapter, chapters.size() - 1));
	}

	@Override
	protected void init() {
		bookWidth = Math.max(Math.min(MIN_WIDTH, width - 8), Math.min(MAX_WIDTH, width - 24));
		bookHeight = Math.max(Math.min(MIN_HEIGHT, height - 20), Math.min(MAX_HEIGHT, height - 36));
		left = (width - bookWidth) / 2;
		top = Math.max(16, (height - bookHeight) / 2);
		previous = addRenderableWidget(Button.builder(Component.literal("<"), button -> turn(-1))
				.bounds(left + SIDE_WIDTH + 8, top + bookHeight - FOOTER + 2, 16, 14).build());
		next = addRenderableWidget(Button.builder(Component.literal(">"), button -> turn(1))
				.bounds(left + bookWidth - 24, top + bookHeight - FOOTER + 2, 16, 14).build());
		revealOpenPage();
	}

	private void openChapter(int index) {
		chapter = index;
		page = 0;
		pageScroll = 0;
		revealOpenPage();
	}

	private void openPage(int index) {
		page = index;
		pageScroll = 0;
	}

	private void turn(int delta) {
		int count = pages().size();
		if (count > 0) {
			openPage(Math.floorMod(page + delta, count));
			revealOpenPage();
		}
	}

	private JsonArray pages() {
		return chapters.isEmpty() ? new JsonArray() : chapters.get(chapter).getAsJsonArray("pages");
	}

	// ------------------------------------------------------------------ the contents list

	private int sideTop() {
		return top + 6;
	}

	private int sideBottom() {
		return top + bookHeight - 6;
	}

	/** Every row of the contents list, positioned before scrolling (relative to the list's top). */
	private List<Row> rows() {
		List<Row> rows = new ArrayList<>();
		int y = 0;
		for (int c = 0; c < chapters.size(); c++) {
			rows.add(new Row(c, -1, y, CHAPTER_ROW));
			y += CHAPTER_ROW;
			if (c == chapter) {
				JsonArray pages = pages();
				for (int p = 0; p < pages.size(); p++) {
					rows.add(new Row(c, p, y, PAGE_ROW));
					y += PAGE_ROW;
				}
				y += 3;
			}
		}
		return rows;
	}

	private static int listHeight(List<Row> rows) {
		if (rows.isEmpty()) {
			return 0;
		}
		Row last = rows.get(rows.size() - 1);
		return last.y() + last.height() + 3;
	}

	/** Scrolls the contents list so the open chapter's heading and its open page are in view. */
	private void revealOpenPage() {
		List<Row> rows = rows();
		int visible = sideBottom() - sideTop();
		for (Row row : rows) {
			if (row.chapter() == chapter && row.page() == page) {
				int headingY = row.y() - (page + 1) * PAGE_ROW;
				if (headingY < sideScroll) {
					sideScroll = headingY;
				}
				if (row.y() + row.height() > sideScroll + visible) {
					sideScroll = row.y() + row.height() - visible;
				}
			}
		}
		sideScroll = Math.max(0, Math.min(sideScroll, Math.max(0, listHeight(rows) - visible)));
	}

	private void extractContents(GuiGraphicsExtractor graphics, int mouseX, int mouseY) {
		List<Row> rows = rows();
		int x0 = left + 5;
		int x1 = left + SIDE_WIDTH - 7;
		int listTop = sideTop();
		int listBottom = sideBottom();
		int visible = listBottom - listTop;
		graphics.enableScissor(x0, listTop, x1, listBottom);
		for (Row row : rows) {
			int y = listTop + row.y() - sideScroll;
			if (y + row.height() < listTop || y > listBottom) {
				continue;
			}
			boolean hover = mouseX >= x0 && mouseX < x1 && mouseY >= Math.max(y, listTop)
					&& mouseY < Math.min(y + row.height(), listBottom);
			if (row.page() < 0) {
				boolean open = row.chapter() == chapter;
				graphics.fill(x0, y, x1, y + row.height() - 1, open ? TAB_SELECTED : hover ? TAB_HOVER : LEATHER_DARK);
				String title = (open ? "▾ " : "▸ ") + chapters.get(row.chapter()).get("title").getAsString();
				graphics.text(font, fit(title, x1 - x0 - 4), x0 + 3, y + 2, TAB_TEXT, false);
			} else {
				boolean selected = row.page() == page;
				if (selected || hover) {
					graphics.fill(x0 + 6, y, x1, y + row.height(), selected ? PAPER_SHADE : TAB_HOVER);
				}
				String title = pages().get(row.page()).getAsJsonObject().get("title").getAsString();
				graphics.text(font, fit(title, x1 - x0 - 12), x0 + 9, y + 1, selected ? INK : TAB_DIM, false);
			}
		}
		graphics.disableScissor();
		// A scroll bar when the list is longer than the book.
		int total = listHeight(rows);
		if (total > visible) {
			int barHeight = Math.max(12, visible * visible / total);
			int barY = listTop + (visible - barHeight) * sideScroll / Math.max(1, total - visible);
			graphics.fill(x1 + 1, listTop, x1 + 3, listBottom, LEATHER_DARK);
			graphics.fill(x1 + 1, barY, x1 + 3, barY + barHeight, BRASS);
		}
	}

	/** The text cut to fit the width, with an ellipsis if anything was cut. */
	private String fit(String text, int maxWidth) {
		if (font.width(text) <= maxWidth) {
			return text;
		}
		String cut = text;
		while (!cut.isEmpty() && font.width(cut + "…") > maxWidth) {
			cut = cut.substring(0, cut.length() - 1);
		}
		return cut + "…";
	}

	// ------------------------------------------------------------------ input

	@Override
	public boolean mouseClicked(MouseButtonEvent event, boolean doubleClick) {
		double mx = event.x();
		double my = event.y();
		if (event.button() == 0 && mx >= left + 5 && mx < left + SIDE_WIDTH - 7 && my >= sideTop() && my < sideBottom()) {
			for (Row row : rows()) {
				int y = sideTop() + row.y() - sideScroll;
				if (my >= y && my < y + row.height()) {
					if (row.page() < 0) {
						openChapter(row.chapter());
					} else {
						openPage(row.page());
					}
					return true;
				}
			}
		}
		return super.mouseClicked(event, doubleClick);
	}

	@Override
	public boolean mouseScrolled(double mouseX, double mouseY, double scrollX, double scrollY) {
		int step = (int) Math.round(-scrollY * SCROLL_STEP);
		if (mouseX < left + SIDE_WIDTH) {
			int visible = sideBottom() - sideTop();
			sideScroll = Math.max(0, Math.min(sideScroll + step, Math.max(0, listHeight(rows()) - visible)));
		} else {
			scrollPage(step);
		}
		return true;
	}

	private void scrollPage(int step) {
		pageScroll = Math.max(0, Math.min(pageScroll + step, Math.max(0, pageHeight - (bodyBottom() - bodyTop()))));
	}

	@Override
	public boolean keyPressed(KeyEvent event) {
		switch (event.input()) {
			case KEY_LEFT -> turn(-1);
			case KEY_RIGHT -> turn(1);
			case KEY_UP -> scrollPage(-SCROLL_STEP);
			case KEY_DOWN -> scrollPage(SCROLL_STEP);
			case KEY_PAGE_UP -> scrollPage(-(bodyBottom() - bodyTop() - SCROLL_STEP));
			case KEY_PAGE_DOWN -> scrollPage(bodyBottom() - bodyTop() - SCROLL_STEP);
			default -> {
				return super.keyPressed(event);
			}
		}
		return true;
	}

	// ------------------------------------------------------------------ drawing

	/** The world blur (drawn once by Screen), then the book: leather cover, brass edge and the paper of the page. */
	@Override
	public void extractBackground(GuiGraphicsExtractor graphics, int mouseX, int mouseY, float delta) {
		super.extractBackground(graphics, mouseX, mouseY, delta);
		graphics.fill(left - 3, top - 3, left + bookWidth + 3, top + bookHeight + 3, BRASS_DARK);
		graphics.fill(left - 2, top - 2, left + bookWidth + 2, top + bookHeight + 2, BRASS);
		graphics.fill(left, top, left + bookWidth, top + bookHeight, LEATHER);
		graphics.fill(left + SIDE_WIDTH, top + 4, left + bookWidth - 4, top + bookHeight - 4, PAPER);
		graphics.fill(left + SIDE_WIDTH, top + 4, left + SIDE_WIDTH + 3, top + bookHeight - 4, PAPER_SHADE);
		graphics.text(font, title, left + (bookWidth - font.width(title)) / 2, top - 13, 0xFFF4E2B0, true);
	}

	private int pageX() {
		return left + SIDE_WIDTH + 10;
	}

	private int textWidth() {
		return bookWidth - SIDE_WIDTH - 24;
	}

	/** The scrolling part of the page: below its title, above the page buttons. */
	private int bodyTop() {
		return top + 30;
	}

	private int bodyBottom() {
		return top + bookHeight - FOOTER - 2;
	}

	@Override
	public void extractRenderState(GuiGraphicsExtractor graphics, int mouseX, int mouseY, float delta) {
		boolean pageable = pages().size() > 1;
		previous.visible = pageable;
		next.visible = pageable;
		// Draws the background (above) and the buttons; the contents and page go on top.
		super.extractRenderState(graphics, mouseX, mouseY, delta);

		if (chapters.isEmpty()) {
			graphics.text(font, "Handbook content missing", pageX(), top + 12, INK, false);
			return;
		}
		extractContents(graphics, mouseX, mouseY);
		JsonArray pages = pages();
		if (pages.isEmpty()) {
			return;
		}
		page = Math.max(0, Math.min(page, pages.size() - 1));
		JsonObject data = pages.get(page).getAsJsonObject();
		// The title stays put; the body scrolls under it.
		int x = pageX();
		item(graphics, data.get("icon").getAsString(), x, top + 8, mouseX, mouseY, true);
		graphics.text(font, fit(data.get("title").getAsString(), textWidth() - 20), x + 20, top + 12, INK, false);
		graphics.fill(x, top + 26, x + textWidth(), top + 27, PAPER_SHADE);

		int bodyTop = bodyTop();
		int bodyBottom = bodyBottom();
		int visible = bodyBottom - bodyTop;
		graphics.enableScissor(x - 2, bodyTop, x + textWidth() + 2, bodyBottom);
		boolean inBody = mouseY >= bodyTop && mouseY < bodyBottom;
		int start = bodyTop - pageScroll;
		pageHeight = extractBody(graphics, data, x, start, mouseX, mouseY, inBody) - start;
		graphics.disableScissor();
		pageScroll = Math.max(0, Math.min(pageScroll, Math.max(0, pageHeight - visible)));
		// A scroll bar when the page is longer than the book.
		if (pageHeight > visible) {
			int barX = left + bookWidth - 10;
			int barHeight = Math.max(12, visible * visible / pageHeight);
			int barY = bodyTop + (visible - barHeight) * pageScroll / Math.max(1, pageHeight - visible);
			graphics.fill(barX, bodyTop, barX + 2, bodyBottom, PAPER_SHADE);
			graphics.fill(barX, barY, barX + 2, barY + barHeight, INK_LIGHT);
		}

		if (pageable) {
			String counter = (page + 1) + " / " + pages.size();
			int middle = left + SIDE_WIDTH + (bookWidth - SIDE_WIDTH) / 2;
			graphics.text(font, counter, middle - font.width(counter) / 2, top + bookHeight - FOOTER + 5, INK_LIGHT, false);
		}
	}

	/** Draws the page's body from {@code y} down; returns where it ends. */
	private int extractBody(GuiGraphicsExtractor graphics, JsonObject data, int x, int y, int mouseX, int mouseY, boolean tooltips) {
		int textWidth = textWidth();
		for (JsonElement paragraph : data.getAsJsonArray("text")) {
			for (FormattedCharSequence line : font.split(Component.literal(paragraph.getAsString()), textWidth)) {
				graphics.text(font, line, x, y, INK, false);
				y += font.lineHeight;
			}
			y += 3;
		}
		y += 2;
		if (data.has("steps")) {
			y = extractSteps(graphics, data.getAsJsonArray("steps"), x, y, mouseX, mouseY, tooltips);
		}
		int bottom = y;
		int recipesX = x;
		if (data.has("craft")) {
			JsonObject craft = data.getAsJsonObject("craft");
			JsonArray grid = craft.getAsJsonArray("grid");
			for (int i = 0; i < 9; i++) {
				int sx = x + (i % 3) * 18;
				int sy = y + (i / 3) * 18;
				graphics.fill(sx, sy, sx + 17, sy + 17, SLOT);
				if (!grid.get(i).isJsonNull()) {
					item(graphics, grid.get(i).getAsString(), sx, sy, mouseX, mouseY, tooltips);
				}
			}
			graphics.text(font, "→", x + 57, y + 22, INK_LIGHT, false);
			graphics.fill(x + 66, y + 17, x + 83, y + 34, SLOT);
			itemWithCount(graphics, craft.get("result").getAsString(), craft.get("count").getAsInt(), x + 66, y + 17,
					mouseX, mouseY, tooltips);
			bottom = y + 54;
			recipesX = x + 92;
			// Recipes go beside the grid when there is room, else under it.
			if (textWidth - 92 < 100) {
				recipesX = x;
				y = bottom + 4;
			}
		}
		if (data.has("recipes")) {
			int ry = y;
			for (JsonElement element : data.getAsJsonArray("recipes")) {
				JsonObject row = element.getAsJsonObject();
				int rx = recipesX;
				for (JsonElement input : row.getAsJsonArray("in")) {
					JsonArray pair = input.getAsJsonArray();
					itemWithCount(graphics, pair.get(0).getAsString(), pair.get(1).getAsInt(), rx, ry, mouseX, mouseY, tooltips);
					rx += 17;
				}
				graphics.text(font, "→", rx + 1, ry + 5, INK_LIGHT, false);
				rx += 10;
				JsonArray out = row.getAsJsonArray("out");
				itemWithCount(graphics, out.get(0).getAsString(), out.get(1).getAsInt(), rx, ry, mouseX, mouseY, tooltips);
				rx += 18;
				if (row.has("extra")) {
					for (JsonElement extra : row.getAsJsonArray("extra")) {
						JsonArray pair = extra.getAsJsonArray();
						item(graphics, pair.get(0).getAsString(), rx, ry, mouseX, mouseY, tooltips);
						String chance = Math.round(pair.get(1).getAsDouble() * 100) + "%";
						graphics.text(font, chance, rx + 16, ry + 5, INK_LIGHT, false);
						rx += 18 + font.width(chance);
					}
				}
				ry += 18;
			}
			bottom = Math.max(bottom, ry);
		}
		return bottom + 4;
	}

	/**
	 * Progression steps: numbered cards in reading order, each an item and its label, with an arrow to the next,
	 * as many to a row as fit.
	 */
	private int extractSteps(GuiGraphicsExtractor graphics, JsonArray steps, int x, int y, int mouseX, int mouseY, boolean tooltips) {
		int columns = Math.max(1, (textWidth() + STEP_GAP) / (STEP_MIN_WIDTH + STEP_GAP));
		int cardWidth = Math.min(STEP_MAX_WIDTH, (textWidth() - (columns - 1) * STEP_GAP) / columns);
		for (int i = 0; i < steps.size(); i++) {
			JsonObject step = steps.get(i).getAsJsonObject();
			int cx = x + (i % columns) * (cardWidth + STEP_GAP);
			int cy = y + (i / columns) * (STEP_HEIGHT + 6);
			graphics.fill(cx, cy, cx + cardWidth, cy + STEP_HEIGHT, PAPER_SHADE);
			graphics.outline(cx, cy, cardWidth, STEP_HEIGHT, SLOT);
			graphics.text(font, String.valueOf(i + 1), cx + 3, cy + 3, INK_LIGHT, false);
			item(graphics, step.get("item").getAsString(), cx + (cardWidth - 16) / 2, cy + 3, mouseX, mouseY, tooltips);
			int ly = cy + 21;
			for (FormattedCharSequence line : font.split(Component.literal(step.get("label").getAsString()), cardWidth - 2)) {
				if (ly + font.lineHeight > cy + STEP_HEIGHT) {
					break;
				}
				graphics.text(font, line, cx + (cardWidth - font.width(line)) / 2, ly, INK, false);
				ly += font.lineHeight;
			}
			if (i + 1 < steps.size() && i % columns != columns - 1) {
				graphics.text(font, "→", cx + cardWidth + 1, cy + STEP_HEIGHT / 2 - 4, INK_LIGHT, false);
			}
		}
		int rows = (steps.size() + columns - 1) / columns;
		return y + rows * (STEP_HEIGHT + 6) + 2;
	}

	private void item(GuiGraphicsExtractor graphics, String id, int x, int y, int mouseX, int mouseY, boolean tooltips) {
		itemWithCount(graphics, id, 1, x, y, mouseX, mouseY, tooltips);
	}

	private void itemWithCount(GuiGraphicsExtractor graphics, String id, int count, int x, int y, int mouseX, int mouseY,
			boolean tooltips) {
		ItemStack stack = new ItemStack(BuiltInRegistries.ITEM.getValue(Identifier.parse(id)), count);
		graphics.item(stack, x, y);
		graphics.itemDecorations(font, stack, x, y);
		if (tooltips && mouseX >= x && mouseX < x + 16 && mouseY >= y && mouseY < y + 16) {
			graphics.setTooltipForNextFrame(font, stack, mouseX, mouseY);
		}
	}
}
