package io.github.jimbozoomer.jugcraft.client;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import io.github.jimbozoomer.jugcraft.Jugcraft;
import java.io.Reader;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.server.packs.resources.Resource;
import net.minecraft.util.FormattedCharSequence;
import net.minecraft.world.item.ItemStack;

/**
 * The Engineer's Handbook screen: chapters on the left, one page at a time on the right, with item
 * icons, a crafting grid and example machine recipes. Content: assets/jugcraft/handbook/en_us.json,
 * generated by tools/handbook.py from the mod's own tables. Reading only; nothing is sent to the server.
 */
public class HandbookScreen extends Screen {
	private static final Identifier CONTENT = Jugcraft.id("handbook/en_us.json");
	private static final int WIDTH = 330;
	private static final int HEIGHT = 190;
	private static final int CHAPTER_WIDTH = 112;

	private static final int BRASS = 0xFFB08A3A;
	private static final int BRASS_DARK = 0xFF6E5220;
	private static final int LEATHER = 0xFF4A2A18;
	private static final int PAPER = 0xFFF1E6CB;
	private static final int PAPER_SHADE = 0xFFE2D2AE;
	private static final int INK = 0xFF3A2A1A;
	private static final int INK_LIGHT = 0xFF7A6040;
	private static final int SLOT = 0xFFD6C49C;

	private final List<JsonObject> chapters = new ArrayList<>();
	private int chapter;
	private int page;
	private int left;
	private int top;
	private Button previous;
	private Button next;

	public HandbookScreen() {
		this(0, 0);
	}

	public HandbookScreen(int chapter, int page) {
		super(Component.translatable("item.jugcraft.engineers_handbook"));
		this.chapter = chapter;
		this.page = page;
		load();
	}

	private void load() {
		Optional<Resource> resource = Minecraft.getInstance().getResourceManager().getResource(CONTENT);
		if (resource.isEmpty()) {
			return;
		}
		try (Reader reader = resource.get().openAsReader()) {
			for (JsonElement element : JsonParser.parseReader(reader).getAsJsonObject().getAsJsonArray("chapters")) {
				chapters.add(element.getAsJsonObject());
			}
		} catch (Exception e) {
			Jugcraft.LOGGER.warn("Could not read the Engineer's Handbook", e);
		}
		chapter = Math.max(0, Math.min(chapter, chapters.size() - 1));
	}

	@Override
	protected void init() {
		left = (width - WIDTH) / 2;
		top = (height - HEIGHT) / 2;
		for (int i = 0; i < chapters.size(); i++) {
			int index = i;
			addRenderableWidget(Button.builder(Component.literal(chapters.get(i).get("title").getAsString()), button -> openChapter(index))
					.bounds(left + 6, top + 10 + i * 18, CHAPTER_WIDTH - 12, 16).build());
		}
		previous = addRenderableWidget(Button.builder(Component.literal("<"), button -> turn(-1))
				.bounds(left + CHAPTER_WIDTH + 8, top + HEIGHT - 20, 16, 14).build());
		next = addRenderableWidget(Button.builder(Component.literal(">"), button -> turn(1))
				.bounds(left + WIDTH - 24, top + HEIGHT - 20, 16, 14).build());
	}

	private void openChapter(int index) {
		chapter = index;
		page = 0;
	}

	private void turn(int delta) {
		int count = pages().size();
		if (count > 0) {
			page = Math.floorMod(page + delta, count);
		}
	}

	private JsonArray pages() {
		return chapters.isEmpty() ? new JsonArray() : chapters.get(chapter).getAsJsonArray("pages");
	}

	/** The world blur (drawn once by Screen), then the book: leather cover, brass edge and the paper of the page. */
	@Override
	public void extractBackground(GuiGraphicsExtractor graphics, int mouseX, int mouseY, float delta) {
		super.extractBackground(graphics, mouseX, mouseY, delta);
		graphics.fill(left - 3, top - 3, left + WIDTH + 3, top + HEIGHT + 3, BRASS_DARK);
		graphics.fill(left - 2, top - 2, left + WIDTH + 2, top + HEIGHT + 2, BRASS);
		graphics.fill(left, top, left + WIDTH, top + HEIGHT, LEATHER);
		graphics.fill(left + CHAPTER_WIDTH, top + 4, left + WIDTH - 4, top + HEIGHT - 4, PAPER);
		graphics.fill(left + CHAPTER_WIDTH, top + 4, left + CHAPTER_WIDTH + 3, top + HEIGHT - 4, PAPER_SHADE);
		graphics.text(font, title, left + (WIDTH - font.width(title)) / 2, top - 13, 0xFFF4E2B0, true);
	}

	@Override
	public void extractRenderState(GuiGraphicsExtractor graphics, int mouseX, int mouseY, float delta) {
		boolean pageable = pages().size() > 1;
		previous.visible = pageable;
		next.visible = pageable;
		// Draws the background (above) and the buttons; the page content goes on top.
		super.extractRenderState(graphics, mouseX, mouseY, delta);

		if (chapters.isEmpty()) {
			graphics.text(font, "Handbook content missing", left + CHAPTER_WIDTH + 10, top + 12, INK, false);
			return;
		}
		JsonArray pages = pages();
		if (pages.isEmpty()) {
			return;
		}
		page = Math.min(page, pages.size() - 1);
		extractPage(graphics, pages.get(page).getAsJsonObject(), mouseX, mouseY);
		if (pageable) {
			String counter = (page + 1) + " / " + pages.size();
			graphics.text(font, counter, left + CHAPTER_WIDTH + (WIDTH - CHAPTER_WIDTH) / 2 - font.width(counter) / 2,
					top + HEIGHT - 17, INK_LIGHT, false);
		}
	}

	private void extractPage(GuiGraphicsExtractor graphics, JsonObject data, int mouseX, int mouseY) {
		int x = left + CHAPTER_WIDTH + 10;
		int y = top + 10;
		int textWidth = WIDTH - CHAPTER_WIDTH - 20;
		item(graphics, data.get("icon").getAsString(), x, y - 4, mouseX, mouseY);
		graphics.text(font, data.get("title").getAsString(), x + 20, y, INK, false);
		y += 16;
		for (JsonElement paragraph : data.getAsJsonArray("text")) {
			for (FormattedCharSequence line : font.split(Component.literal(paragraph.getAsString()), textWidth)) {
				graphics.text(font, line, x, y, INK, false);
				y += font.lineHeight;
			}
			y += 3;
		}
		y += 2;
		int recipesX = x;
		if (data.has("craft")) {
			JsonObject craft = data.getAsJsonObject("craft");
			JsonArray grid = craft.getAsJsonArray("grid");
			for (int i = 0; i < 9; i++) {
				int sx = x + (i % 3) * 18;
				int sy = y + (i / 3) * 18;
				graphics.fill(sx, sy, sx + 17, sy + 17, SLOT);
				if (!grid.get(i).isJsonNull()) {
					item(graphics, grid.get(i).getAsString(), sx, sy, mouseX, mouseY);
				}
			}
			graphics.text(font, "→", x + 57, y + 22, INK_LIGHT, false);
			graphics.fill(x + 66, y + 17, x + 83, y + 34, SLOT);
			itemWithCount(graphics, craft.get("result").getAsString(), craft.get("count").getAsInt(), x + 66, y + 17, mouseX, mouseY);
			recipesX = x + 92;
		}
		if (data.has("recipes")) {
			int ry = y;
			for (JsonElement element : data.getAsJsonArray("recipes")) {
				JsonObject row = element.getAsJsonObject();
				int rx = recipesX;
				for (JsonElement input : row.getAsJsonArray("in")) {
					JsonArray pair = input.getAsJsonArray();
					itemWithCount(graphics, pair.get(0).getAsString(), pair.get(1).getAsInt(), rx, ry, mouseX, mouseY);
					rx += 17;
				}
				graphics.text(font, "→", rx + 1, ry + 5, INK_LIGHT, false);
				rx += 10;
				JsonArray out = row.getAsJsonArray("out");
				itemWithCount(graphics, out.get(0).getAsString(), out.get(1).getAsInt(), rx, ry, mouseX, mouseY);
				rx += 18;
				if (row.has("extra")) {
					for (JsonElement extra : row.getAsJsonArray("extra")) {
						JsonArray pair = extra.getAsJsonArray();
						item(graphics, pair.get(0).getAsString(), rx, ry, mouseX, mouseY);
						String chance = Math.round(pair.get(1).getAsDouble() * 100) + "%";
						graphics.text(font, chance, rx + 16, ry + 5, INK_LIGHT, false);
						rx += 18 + font.width(chance);
					}
				}
				ry += 18;
			}
		}
	}

	private void item(GuiGraphicsExtractor graphics, String id, int x, int y, int mouseX, int mouseY) {
		itemWithCount(graphics, id, 1, x, y, mouseX, mouseY);
	}

	private void itemWithCount(GuiGraphicsExtractor graphics, String id, int count, int x, int y, int mouseX, int mouseY) {
		ItemStack stack = new ItemStack(BuiltInRegistries.ITEM.getValue(Identifier.parse(id)), count);
		graphics.item(stack, x, y);
		graphics.itemDecorations(font, stack, x, y);
		if (mouseX >= x && mouseX < x + 16 && mouseY >= y && mouseY < y + 16) {
			graphics.setTooltipForNextFrame(font, stack, mouseX, mouseY);
		}
	}
}
