package io.github.jimbozoomer.jugcraft.agriculture;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.properties.IntegerProperty;
import net.minecraft.world.phys.shapes.Shapes;
import net.minecraft.world.phys.shapes.VoxelShape;
import org.jspecify.annotations.Nullable;

/**
 * A graveyard building of pack 3 (tools/graveyard.py, BUILDINGS): the family mausoleum, the lych gate, the cemetery
 * gateway and the columbarium. It is a {@link HeadstoneBlock} of many parts, one block for each cell it fills, placed,
 * broken, weathered, waxed and inscribed as one. Its {@link Building} layout (cells, the shape of each part, where each
 * inscription is cut and which part cuts which, the light each part gives) is generated by tools/graveyard_data.py into
 * {@code /jugcraft/graveyard_buildings.json}. The cells a doorway, an aisle or a room needs are left out of it, so it
 * can be walked into, and a door or gate of the player's own hung in its openings.
 *
 * <p>Each building has a part property with exactly as many values as it has parts, so that the biggest does not
 * give the smallest thousands of states it never uses; the property is handed over while the block is made
 * ({@link #create}), as the state definition is built before the block's own fields are set.
 */
public class GraveyardBuildingBlock extends HeadstoneBlock {
	private static final ThreadLocal<IntegerProperty> MAKING = new ThreadLocal<>();

	private final @Nullable IntegerProperty part;

	private GraveyardBuildingBlock(Properties properties, Building building) {
		super(properties, building);
		part = building.part();
	}

	public static GraveyardBuildingBlock create(Properties properties, Building building) {
		MAKING.set(building.part());
		try {
			return new GraveyardBuildingBlock(properties, building);
		} finally {
			MAKING.remove();
		}
	}

	@Override
	public IntegerProperty partProperty() {
		return part != null ? part : MAKING.get();
	}

	public Building building() {
		return (Building) layout();
	}

	@Override
	public @Nullable BlockEntity newBlockEntity(BlockPos pos, BlockState state) {
		return part(state) == 0 ? new HeadstoneBlockEntity(JugcraftAgriculture.GRAVEYARD_BUILDING_ENTITY, pos, state) : null;
	}

	/**
	 * A building's layout, read from /jugcraft/graveyard_buildings.json: its id and stone, whether it is timber, its cells
	 * (right, up, back from part 0), each part's boxes facing north, each inscription's place, which inscription each
	 * part cuts, and the light each part gives.
	 */
	public static final class Building implements Layout {
		private final String id;
		private final Stone stone;
		private final int[][] cells;
		private final VoxelShape[][] shapes;
		private final List<Text> texts;
		private final int[] slots;
		private final int[] lights;
		private final boolean wooden;
		private final IntegerProperty part;

		private Building(String id, Stone stone, int[][] cells, VoxelShape[][] shapes, List<Text> texts, int[] slots, int[] lights,
				boolean wooden) {
			this.id = id;
			this.wooden = wooden;
			this.stone = stone;
			this.cells = cells;
			this.shapes = shapes;
			this.texts = texts;
			this.slots = slots;
			this.lights = lights;
			part = IntegerProperty.create("part", 0, cells.length - 1);
		}

		/** The building {@code json} describes (one entry of graveyard_buildings.json). */
		public static Building read(JsonObject json) {
			String id = json.get("id").getAsString();
			Stone stone = Stone.valueOf(json.get("stone").getAsString().toUpperCase(Locale.ROOT));
			JsonArray cellList = json.getAsJsonArray("cells");
			int[][] cells = new int[cellList.size()][];
			for (int i = 0; i < cells.length; i++) {
				JsonArray cell = cellList.get(i).getAsJsonArray();
				cells[i] = new int[] {cell.get(0).getAsInt(), cell.get(1).getAsInt(), cell.get(2).getAsInt()};
			}
			if (cells.length < 2 || cells[0][0] != 0 || cells[0][1] != 0 || cells[0][2] != 0) {
				throw new IllegalStateException("Graveyard building " + id + " needs part 0 at its own cell and more parts");
			}
			JsonArray shapeList = json.getAsJsonArray("shapes");
			VoxelShape[][] shapes = new VoxelShape[cells.length][4];
			for (int i = 0; i < cells.length; i++) {
				JsonArray boxes = shapeList.get(i).getAsJsonArray();
				for (Direction facing : Direction.Plane.HORIZONTAL) {
					VoxelShape shape = Shapes.empty();
					for (JsonElement element : boxes) {
						JsonArray box = element.getAsJsonArray();
						double[] b = new double[6];
						for (int k = 0; k < 6; k++) {
							b[k] = box.get(k).getAsDouble();
						}
						shape = Shapes.or(shape, Style.turned(b, facing));
					}
					shapes[i][facing.get2DDataValue()] = shape.optimize();
				}
			}
			List<Text> texts = new ArrayList<>();
			for (JsonElement element : json.getAsJsonArray("texts")) {
				JsonObject text = element.getAsJsonObject();
				texts.add(new Text(Face.valueOf(text.get("face").getAsString()), text.get("x").getAsFloat(), text.get("y").getAsFloat(),
						text.get("z").getAsFloat(), text.get("width").getAsFloat(), text.get("height").getAsFloat(),
						text.get("max_scale").getAsFloat()));
			}
			if (texts.isEmpty() || texts.size() > 1 + HeadstoneBlockEntity.MORE) {
				throw new IllegalStateException("Graveyard building " + id + " has " + texts.size() + " inscriptions");
			}
			int[] slots = ints(json.getAsJsonArray("slots"), cells.length);
			int[] lights = ints(json.getAsJsonArray("light"), cells.length);
			for (int slot : slots) {
				if (slot < 0 || slot >= texts.size()) {
					throw new IllegalStateException("Graveyard building " + id + " has a part cutting inscription " + slot);
				}
			}
			return new Building(id, stone, cells, shapes, List.copyOf(texts), slots, lights, "wood".equals(json.get("sound").getAsString()));
		}

		private static int[] ints(JsonArray array, int size) {
			if (array.size() != size) {
				throw new IllegalStateException("Expected " + size + " values, found " + array.size());
			}
			int[] out = new int[size];
			for (int i = 0; i < size; i++) {
				out[i] = array.get(i).getAsInt();
			}
			return out;
		}

		public IntegerProperty part() {
			return part;
		}

		/** Whether it is built mostly of timber (the lych gate), so sounds and burns as wood does. */
		public boolean wooden() {
			return wooden;
		}

		@Override
		public String id() {
			return id;
		}

		@Override
		public Stone stone() {
			return stone;
		}

		@Override
		public int[][] cells() {
			return cells;
		}

		@Override
		public VoxelShape shape(int part, Direction facing) {
			return shapes[part][facing.get2DDataValue()];
		}

		@Override
		public List<Text> texts() {
			return texts;
		}

		@Override
		public int slot(int part) {
			return slots[part];
		}

		@Override
		public int light(int part) {
			return lights[part];
		}
	}
}
