package io.github.jimbozoomer.jugcraft.client.compat;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import io.github.jimbozoomer.jugcraft.Jugcraft;
import java.io.Reader;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Optional;
import mezz.jei.api.IModPlugin;
import mezz.jei.api.gui.builder.IRecipeLayoutBuilder;
import mezz.jei.api.gui.drawable.IDrawable;
import mezz.jei.api.gui.ingredient.IRecipeSlotsView;
import mezz.jei.api.gui.widgets.IRecipeExtrasBuilder;
import mezz.jei.api.helpers.IGuiHelper;
import mezz.jei.api.recipe.IFocusGroup;
import mezz.jei.api.recipe.category.IRecipeCategory;
import mezz.jei.api.recipe.types.IRecipeType;
import mezz.jei.api.registration.IRecipeCatalystRegistration;
import mezz.jei.api.registration.IRecipeCategoryRegistration;
import mezz.jei.api.registration.IRecipeRegistration;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.core.Holder;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.server.packs.resources.Resource;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.material.Fluid;

/**
 * JEI integration (optional: loaded by JEI through the "jei_mod_plugin" entrypoint, never otherwise).
 * One category per Jugcraft machine, with its recipes and the machine as the catalyst. Recipes are
 * server data in 26.x, so the list comes from assets/jugcraft/recipe_view.json, generated by
 * tools/recipe_view.py from the same tables as the recipe data.
 */
public class JugcraftJeiPlugin implements IModPlugin {
	private static final Identifier DATA = Jugcraft.id("recipe_view.json");
	private static final int TEXT = 0xFF404040;

	/** One recipe: input slots (a tag shows all its items), the result, byproducts with chances, and time. */
	public record ViewRecipe(List<List<ItemStack>> inputs, ItemStack output, List<ItemStack> extras, List<Float> chances, int ticks) {
	}

	private record Machine(Item block, IRecipeType<ViewRecipe> type, List<ViewRecipe> recipes) {
	}

	/** A fluid machine's recipe (FLUID_RECIPES in tools/petro.py): items and fluids in, fluids and items out, in mB. */
	public record FluidViewRecipe(List<List<ItemStack>> items, List<FluidAmount> fluids, List<FluidAmount> fluidResults,
			List<ItemStack> results, int ticks) {
	}

	public record FluidAmount(Fluid fluid, int mb) {
	}

	private record FluidMachine(Item block, IRecipeType<FluidViewRecipe> type, List<FluidViewRecipe> recipes) {
	}

	private List<Machine> machines;
	private List<FluidMachine> fluidMachines = new ArrayList<>();
	/** JEI's fluid amount for one bucket on this platform (81,000 droplets on Fabric). */
	private static long bucketVolume = 1000;

	@Override
	public Identifier getPluginUid() {
		return Jugcraft.id("jei");
	}

	private List<Machine> machines() {
		if (machines == null) {
			machines = load();
		}
		return machines;
	}

	@Override
	public void registerCategories(IRecipeCategoryRegistration registration) {
		machines = load(); // Fresh on every JEI reload, so recipes and categories use the same types.
		fluidMachines = loadFluidMachines();
		bucketVolume = registration.getJeiHelpers().getPlatformFluidHelper().bucketVolume();
		IGuiHelper gui = registration.getJeiHelpers().getGuiHelper();
		for (Machine machine : machines) {
			registration.addRecipeCategories(new MachineCategory(gui, machine));
		}
		for (FluidMachine machine : fluidMachines) {
			registration.addRecipeCategories(new FluidMachineCategory(gui, machine));
		}
	}

	@Override
	public void registerRecipes(IRecipeRegistration registration) {
		for (Machine machine : machines()) {
			registration.addRecipes(machine.type(), machine.recipes());
		}
		for (FluidMachine machine : fluidMachines) {
			registration.addRecipes(machine.type(), machine.recipes());
		}
	}

	@Override
	public void registerRecipeCatalysts(IRecipeCatalystRegistration registration) {
		for (Machine machine : machines()) {
			registration.addCraftingStation(machine.type(), machine.block());
		}
		for (FluidMachine machine : fluidMachines) {
			registration.addCraftingStation(machine.type(), machine.block());
		}
	}

	private static List<Machine> load() {
		List<Machine> result = new ArrayList<>();
		Optional<Resource> resource = Minecraft.getInstance().getResourceManager().getResource(DATA);
		if (resource.isEmpty()) {
			return result;
		}
		try (Reader reader = resource.get().openAsReader()) {
			for (JsonElement element : JsonParser.parseReader(reader).getAsJsonObject().getAsJsonArray("machines")) {
				JsonObject machine = element.getAsJsonObject();
				Item block = BuiltInRegistries.ITEM.getValue(Identifier.parse(machine.get("block").getAsString()));
				IRecipeType<ViewRecipe> type = IRecipeType.create(Jugcraft.id(machine.get("type").getAsString()), ViewRecipe.class);
				List<ViewRecipe> recipes = new ArrayList<>();
				for (JsonElement row : machine.getAsJsonArray("recipes")) {
					recipes.add(recipe(row.getAsJsonObject()));
				}
				result.add(new Machine(block, type, recipes));
			}
		} catch (Exception e) {
			Jugcraft.LOGGER.warn("Could not read Jugcraft's recipe list for JEI", e);
		}
		return result;
	}

	private static List<FluidMachine> loadFluidMachines() {
		List<FluidMachine> result = new ArrayList<>();
		Optional<Resource> resource = Minecraft.getInstance().getResourceManager().getResource(DATA);
		if (resource.isEmpty()) {
			return result;
		}
		try (Reader reader = resource.get().openAsReader()) {
			JsonObject root = JsonParser.parseReader(reader).getAsJsonObject();
			if (!root.has("fluid_machines")) {
				return result;
			}
			for (JsonElement element : root.getAsJsonArray("fluid_machines")) {
				JsonObject machine = element.getAsJsonObject();
				Item block = item(machine.get("block").getAsString());
				IRecipeType<FluidViewRecipe> type = IRecipeType.create(Jugcraft.id(machine.get("type").getAsString()), FluidViewRecipe.class);
				List<FluidViewRecipe> recipes = new ArrayList<>();
				for (JsonElement row : machine.getAsJsonArray("recipes")) {
					JsonObject recipe = row.getAsJsonObject();
					List<List<ItemStack>> items = new ArrayList<>();
					for (JsonElement input : recipe.getAsJsonArray("items")) {
						JsonArray pair = input.getAsJsonArray();
						items.add(stacks(pair.get(0).getAsString(), pair.get(1).getAsInt()));
					}
					List<ItemStack> results = new ArrayList<>();
					for (JsonElement output : recipe.getAsJsonArray("results")) {
						JsonArray pair = output.getAsJsonArray();
						results.add(new ItemStack(item(pair.get(0).getAsString()), pair.get(1).getAsInt()));
					}
					recipes.add(new FluidViewRecipe(items, fluids(recipe.getAsJsonArray("fluids")),
							fluids(recipe.getAsJsonArray("fluid_results")), results, recipe.get("ticks").getAsInt()));
				}
				result.add(new FluidMachine(block, type, recipes));
			}
		} catch (Exception e) {
			Jugcraft.LOGGER.warn("Could not read Jugcraft's fluid recipe list for JEI", e);
		}
		return result;
	}

	private static List<FluidAmount> fluids(JsonArray array) {
		List<FluidAmount> amounts = new ArrayList<>();
		for (JsonElement entry : array) {
			JsonArray pair = entry.getAsJsonArray();
			amounts.add(new FluidAmount(BuiltInRegistries.FLUID.getValue(Identifier.parse(pair.get(0).getAsString())),
					pair.get(1).getAsInt()));
		}
		return amounts;
	}

	private static ViewRecipe recipe(JsonObject row) {
		List<List<ItemStack>> inputs = new ArrayList<>();
		for (JsonElement input : row.getAsJsonArray("in")) {
			JsonArray pair = input.getAsJsonArray();
			inputs.add(stacks(pair.get(0).getAsString(), pair.get(1).getAsInt()));
		}
		JsonArray out = row.getAsJsonArray("out");
		ItemStack output = new ItemStack(item(out.get(0).getAsString()), out.get(1).getAsInt());
		List<ItemStack> extras = new ArrayList<>();
		List<Float> chances = new ArrayList<>();
		for (JsonElement extra : row.getAsJsonArray("extra")) {
			JsonArray values = extra.getAsJsonArray();
			extras.add(new ItemStack(item(values.get(0).getAsString()), values.get(1).getAsInt()));
			chances.add(values.get(2).getAsFloat());
		}
		return new ViewRecipe(inputs, output, extras, chances, row.get("ticks").getAsInt());
	}

	private static Item item(String id) {
		return BuiltInRegistries.ITEM.getValue(Identifier.parse(id));
	}

	/** Every item a recipe reference stands for: one item, or all items in a tag. */
	private static List<ItemStack> stacks(String ref, int count) {
		List<ItemStack> stacks = new ArrayList<>();
		if (ref.startsWith("#")) {
			TagKey<Item> tag = TagKey.create(Registries.ITEM, Identifier.parse(ref.substring(1)));
			BuiltInRegistries.ITEM.get(tag).ifPresent(set -> {
				for (Holder<Item> holder : set) {
					stacks.add(new ItemStack(holder, count));
				}
			});
		} else {
			stacks.add(new ItemStack(item(ref), count));
		}
		return stacks;
	}

	/** A machine's recipes: inputs, a progress arrow, the result, then byproducts with their chance. */
	private static final class MachineCategory implements IRecipeCategory<ViewRecipe> {
		private static final int SLOT_Y = 6;
		private final Machine machine;
		private final IDrawable icon;

		MachineCategory(IGuiHelper gui, Machine machine) {
			this.machine = machine;
			this.icon = gui.createDrawableItemLike(machine.block());
		}

		@Override
		public IRecipeType<ViewRecipe> getRecipeType() {
			return machine.type();
		}

		@Override
		public Component getTitle() {
			return new ItemStack(machine.block()).getHoverName();
		}

		@Override
		public int getWidth() {
			return 164;
		}

		@Override
		public int getHeight() {
			return 38;
		}

		@Override
		public IDrawable getIcon() {
			return icon;
		}

		@Override
		public void setRecipe(IRecipeLayoutBuilder builder, ViewRecipe recipe, IFocusGroup focuses) {
			for (int i = 0; i < recipe.inputs().size(); i++) {
				builder.addInputSlot(i * 18, SLOT_Y).setStandardSlotBackground().addItemStacks(recipe.inputs().get(i));
			}
			builder.addOutputSlot(92, SLOT_Y).setOutputSlotBackground().add(recipe.output());
			for (int i = 0; i < recipe.extras().size(); i++) {
				builder.addOutputSlot(118 + i * 24, SLOT_Y).setStandardSlotBackground().add(recipe.extras().get(i));
			}
		}

		@Override
		public void createRecipeExtras(IRecipeExtrasBuilder builder, ViewRecipe recipe, IFocusGroup focuses) {
			builder.addAnimatedRecipeArrow(recipe.ticks()).setPosition(60, SLOT_Y + 1);
		}

		@Override
		public void draw(ViewRecipe recipe, IRecipeSlotsView slots, GuiGraphicsExtractor graphics, double mouseX, double mouseY) {
			var font = Minecraft.getInstance().font;
			graphics.text(font, String.format(Locale.ROOT, "%.1f s", recipe.ticks() / 20.0), 0, 28, TEXT, false);
			for (int i = 0; i < recipe.chances().size(); i++) {
				String chance = Math.round(recipe.chances().get(i) * 100) + "%";
				graphics.text(font, chance, 118 + i * 24 + 9 - font.width(chance) / 2, 28, TEXT, false);
			}
		}
	}

	/** A fluid machine's recipes: items, then fluids in; a progress arrow; fluids, then items out. */
	private static final class FluidMachineCategory implements IRecipeCategory<FluidViewRecipe> {
		private static final int SLOT_Y = 6;
		private final FluidMachine machine;
		private final IDrawable icon;

		FluidMachineCategory(IGuiHelper gui, FluidMachine machine) {
			this.machine = machine;
			this.icon = gui.createDrawableItemLike(machine.block());
		}

		@Override
		public IRecipeType<FluidViewRecipe> getRecipeType() {
			return machine.type();
		}

		@Override
		public Component getTitle() {
			return new ItemStack(machine.block()).getHoverName();
		}

		@Override
		public int getWidth() {
			return 164;
		}

		@Override
		public int getHeight() {
			return 38;
		}

		@Override
		public IDrawable getIcon() {
			return icon;
		}

		@Override
		public void setRecipe(IRecipeLayoutBuilder builder, FluidViewRecipe recipe, IFocusGroup focuses) {
			int x = 0;
			for (List<ItemStack> input : recipe.items()) {
				builder.addInputSlot(x, SLOT_Y).setStandardSlotBackground().addItemStacks(input);
				x += 18;
			}
			for (FluidAmount fluid : recipe.fluids()) {
				builder.addInputSlot(x, SLOT_Y).setStandardSlotBackground().add(fluid.fluid(), fluid.mb() * bucketVolume / 1000);
				x += 18;
			}
			x = 92;
			for (FluidAmount fluid : recipe.fluidResults()) {
				builder.addOutputSlot(x, SLOT_Y).setOutputSlotBackground().add(fluid.fluid(), fluid.mb() * bucketVolume / 1000);
				x += 18;
			}
			for (ItemStack result : recipe.results()) {
				builder.addOutputSlot(x, SLOT_Y).setOutputSlotBackground().add(result);
				x += 18;
			}
		}

		@Override
		public void createRecipeExtras(IRecipeExtrasBuilder builder, FluidViewRecipe recipe, IFocusGroup focuses) {
			builder.addAnimatedRecipeArrow(recipe.ticks()).setPosition(60, SLOT_Y + 1);
		}

		@Override
		public void draw(FluidViewRecipe recipe, IRecipeSlotsView slots, GuiGraphicsExtractor graphics, double mouseX, double mouseY) {
			var font = Minecraft.getInstance().font;
			graphics.text(font, String.format(Locale.ROOT, "%.1f s", recipe.ticks() / 20.0), 0, 28, TEXT, false);
		}
	}
}
