"""Vanilla 26.3 Overworld biome layouts that the biomes branch's biomes start from (tools/biomes.py).

Functional references only, by ID: each base's placed features per generation step, carvers, mob spawns
(type, weight, group size), music and sky colour, as vanilla 26.3's own biome of that name lists them, so a Jugcraft
biome generates its ores, caves, lakes and springs exactly as the vanilla biome it replaces. Biomes swap in their own
trees and plants (tools/biomes.py). No Mojang file is copied; regenerate from vanilla's data if a version changes them.
"""

BASES = {'birch_forest': {'carvers': ['minecraft:cave', 'minecraft:cave_extra_underground', 'minecraft:canyon'],
                  'music': 'minecraft:music.overworld.forest',
                  'sky_color': '#7aa5ff',
                  'spawns': {'ambient': [{'count': 8, 'type': 'minecraft:bat', 'weight': 10}],
                             'creature': [{'count': 4, 'type': 'minecraft:sheep', 'weight': 12},
                                          {'count': 4, 'type': 'minecraft:pig', 'weight': 10},
                                          {'count': 4, 'type': 'minecraft:chicken', 'weight': 10},
                                          {'count': 4, 'type': 'minecraft:cow', 'weight': 8}],
                             'monster': [{'count': 4, 'type': 'minecraft:spider', 'weight': 100},
                                         {'count': 4, 'type': 'minecraft:zombie', 'weight': 95},
                                         {'count': 1, 'type': 'minecraft:zombie_villager', 'weight': 5},
                                         {'count': 4, 'type': 'minecraft:skeleton', 'weight': 100},
                                         {'count': 4, 'type': 'minecraft:creeper', 'weight': 100},
                                         {'count': 4, 'type': 'minecraft:slime', 'weight': 100},
                                         {'count': {'max_inclusive': 4,
                                                    'min_inclusive': 1,
                                                    'type': 'minecraft:uniform'},
                                          'type': 'minecraft:enderman',
                                          'weight': 10},
                                         {'count': 1, 'type': 'minecraft:witch', 'weight': 5}],
                             'underground_water_creature': [{'count': {'max_inclusive': 6,
                                                                       'min_inclusive': 4,
                                                                       'type': 'minecraft:uniform'},
                                                             'type': 'minecraft:glow_squid',
                                                             'weight': 10}]},
                  'steps': [[],
                            ['minecraft:lake_lava_underground', 'minecraft:lake_lava_surface'],
                            ['minecraft:amethyst_geode'],
                            ['minecraft:monster_room', 'minecraft:monster_room_deep'],
                            [],
                            [],
                            ['minecraft:ore_dirt',
                             'minecraft:ore_gravel',
                             'minecraft:ore_granite_upper',
                             'minecraft:ore_granite_lower',
                             'minecraft:ore_diorite_upper',
                             'minecraft:ore_diorite_lower',
                             'minecraft:ore_andesite_upper',
                             'minecraft:ore_andesite_lower',
                             'minecraft:ore_tuff',
                             'minecraft:ore_coal_upper',
                             'minecraft:ore_coal_lower',
                             'minecraft:ore_iron_upper',
                             'minecraft:ore_iron_middle',
                             'minecraft:ore_iron_small',
                             'minecraft:ore_gold',
                             'minecraft:ore_gold_lower',
                             'minecraft:ore_redstone',
                             'minecraft:ore_redstone_lower',
                             'minecraft:ore_diamond',
                             'minecraft:ore_diamond_medium',
                             'minecraft:ore_diamond_large',
                             'minecraft:ore_diamond_buried',
                             'minecraft:ore_lapis',
                             'minecraft:ore_lapis_buried',
                             'minecraft:ore_copper',
                             'minecraft:underwater_magma',
                             'minecraft:disk_sand',
                             'minecraft:disk_clay',
                             'minecraft:disk_gravel'],
                            [],
                            ['minecraft:spring_water', 'minecraft:spring_lava'],
                            ['minecraft:glow_lichen',
                             'minecraft:forest_flowers',
                             'minecraft:wildflowers_birch_forest',
                             'minecraft:trees_birch',
                             'minecraft:patch_bush',
                             'minecraft:flower_default',
                             'minecraft:patch_grass_forest',
                             'minecraft:brown_mushroom_normal',
                             'minecraft:red_mushroom_normal',
                             'minecraft:patch_pumpkin',
                             'minecraft:patch_sugar_cane',
                             'minecraft:patch_firefly_bush_near_water'],
                            ['minecraft:freeze_top_layer']]},
 'forest': {'carvers': ['minecraft:cave', 'minecraft:cave_extra_underground', 'minecraft:canyon'],
            'music': 'minecraft:music.overworld.forest',
            'sky_color': '#79a6ff',
            'spawns': {'ambient': [{'count': 8, 'type': 'minecraft:bat', 'weight': 10}],
                       'creature': [{'count': 4, 'type': 'minecraft:sheep', 'weight': 12},
                                    {'count': 4, 'type': 'minecraft:pig', 'weight': 10},
                                    {'count': 4, 'type': 'minecraft:chicken', 'weight': 10},
                                    {'count': 4, 'type': 'minecraft:cow', 'weight': 8},
                                    {'count': 4, 'type': 'minecraft:wolf', 'weight': 5}],
                       'monster': [{'count': 4, 'type': 'minecraft:spider', 'weight': 100},
                                   {'count': 4, 'type': 'minecraft:zombie', 'weight': 95},
                                   {'count': 1, 'type': 'minecraft:zombie_villager', 'weight': 5},
                                   {'count': 4, 'type': 'minecraft:skeleton', 'weight': 100},
                                   {'count': 4, 'type': 'minecraft:creeper', 'weight': 100},
                                   {'count': 4, 'type': 'minecraft:slime', 'weight': 100},
                                   {'count': {'max_inclusive': 4, 'min_inclusive': 1, 'type': 'minecraft:uniform'},
                                    'type': 'minecraft:enderman',
                                    'weight': 10},
                                   {'count': 1, 'type': 'minecraft:witch', 'weight': 5}],
                       'underground_water_creature': [{'count': {'max_inclusive': 6,
                                                                 'min_inclusive': 4,
                                                                 'type': 'minecraft:uniform'},
                                                       'type': 'minecraft:glow_squid',
                                                       'weight': 10}]},
            'steps': [[],
                      ['minecraft:lake_lava_underground', 'minecraft:lake_lava_surface'],
                      ['minecraft:amethyst_geode'],
                      ['minecraft:monster_room', 'minecraft:monster_room_deep'],
                      [],
                      [],
                      ['minecraft:ore_dirt',
                       'minecraft:ore_gravel',
                       'minecraft:ore_granite_upper',
                       'minecraft:ore_granite_lower',
                       'minecraft:ore_diorite_upper',
                       'minecraft:ore_diorite_lower',
                       'minecraft:ore_andesite_upper',
                       'minecraft:ore_andesite_lower',
                       'minecraft:ore_tuff',
                       'minecraft:ore_coal_upper',
                       'minecraft:ore_coal_lower',
                       'minecraft:ore_iron_upper',
                       'minecraft:ore_iron_middle',
                       'minecraft:ore_iron_small',
                       'minecraft:ore_gold',
                       'minecraft:ore_gold_lower',
                       'minecraft:ore_redstone',
                       'minecraft:ore_redstone_lower',
                       'minecraft:ore_diamond',
                       'minecraft:ore_diamond_medium',
                       'minecraft:ore_diamond_large',
                       'minecraft:ore_diamond_buried',
                       'minecraft:ore_lapis',
                       'minecraft:ore_lapis_buried',
                       'minecraft:ore_copper',
                       'minecraft:underwater_magma',
                       'minecraft:disk_sand',
                       'minecraft:disk_clay',
                       'minecraft:disk_gravel'],
                      [],
                      ['minecraft:spring_water', 'minecraft:spring_lava'],
                      ['minecraft:glow_lichen',
                       'minecraft:forest_flowers',
                       'minecraft:trees_birch_and_oak_leaf_litter',
                       'minecraft:patch_bush',
                       'minecraft:flower_default',
                       'minecraft:patch_grass_forest',
                       'minecraft:brown_mushroom_normal',
                       'minecraft:red_mushroom_normal',
                       'minecraft:patch_pumpkin',
                       'minecraft:patch_sugar_cane',
                       'minecraft:patch_firefly_bush_near_water'],
                      ['minecraft:freeze_top_layer']]},
 'plains': {'carvers': ['minecraft:cave', 'minecraft:cave_extra_underground', 'minecraft:canyon'],
            'sky_color': '#78a7ff',
            'spawns': {'ambient': [{'count': 8, 'type': 'minecraft:bat', 'weight': 10}],
                       'creature': [{'count': 4, 'type': 'minecraft:sheep', 'weight': 12},
                                    {'count': 4, 'type': 'minecraft:pig', 'weight': 10},
                                    {'count': 4, 'type': 'minecraft:chicken', 'weight': 10},
                                    {'count': 4, 'type': 'minecraft:cow', 'weight': 8},
                                    {'count': {'max_inclusive': 6, 'min_inclusive': 2, 'type': 'minecraft:uniform'},
                                     'type': 'minecraft:horse',
                                     'weight': 5},
                                    {'count': {'max_inclusive': 3, 'min_inclusive': 1, 'type': 'minecraft:uniform'},
                                     'type': 'minecraft:donkey',
                                     'weight': 1}],
                       'monster': [{'count': 4, 'type': 'minecraft:spider', 'weight': 100},
                                   {'count': 4, 'type': 'minecraft:zombie', 'weight': 90},
                                   {'count': 1, 'type': 'minecraft:zombie_villager', 'weight': 5},
                                   {'count': 1, 'type': 'minecraft:zombie_horse', 'weight': 5},
                                   {'count': 4, 'type': 'minecraft:skeleton', 'weight': 100},
                                   {'count': 4, 'type': 'minecraft:creeper', 'weight': 100},
                                   {'count': 4, 'type': 'minecraft:slime', 'weight': 100},
                                   {'count': {'max_inclusive': 4, 'min_inclusive': 1, 'type': 'minecraft:uniform'},
                                    'type': 'minecraft:enderman',
                                    'weight': 10},
                                   {'count': 1, 'type': 'minecraft:witch', 'weight': 5}],
                       'underground_water_creature': [{'count': {'max_inclusive': 6,
                                                                 'min_inclusive': 4,
                                                                 'type': 'minecraft:uniform'},
                                                       'type': 'minecraft:glow_squid',
                                                       'weight': 10}]},
            'steps': [[],
                      ['minecraft:lake_lava_underground', 'minecraft:lake_lava_surface'],
                      ['minecraft:amethyst_geode'],
                      ['minecraft:monster_room', 'minecraft:monster_room_deep'],
                      [],
                      [],
                      ['minecraft:ore_dirt',
                       'minecraft:ore_gravel',
                       'minecraft:ore_granite_upper',
                       'minecraft:ore_granite_lower',
                       'minecraft:ore_diorite_upper',
                       'minecraft:ore_diorite_lower',
                       'minecraft:ore_andesite_upper',
                       'minecraft:ore_andesite_lower',
                       'minecraft:ore_tuff',
                       'minecraft:ore_coal_upper',
                       'minecraft:ore_coal_lower',
                       'minecraft:ore_iron_upper',
                       'minecraft:ore_iron_middle',
                       'minecraft:ore_iron_small',
                       'minecraft:ore_gold',
                       'minecraft:ore_gold_lower',
                       'minecraft:ore_redstone',
                       'minecraft:ore_redstone_lower',
                       'minecraft:ore_diamond',
                       'minecraft:ore_diamond_medium',
                       'minecraft:ore_diamond_large',
                       'minecraft:ore_diamond_buried',
                       'minecraft:ore_lapis',
                       'minecraft:ore_lapis_buried',
                       'minecraft:ore_copper',
                       'minecraft:underwater_magma',
                       'minecraft:disk_sand',
                       'minecraft:disk_clay',
                       'minecraft:disk_gravel'],
                      [],
                      ['minecraft:spring_water', 'minecraft:spring_lava'],
                      ['minecraft:glow_lichen',
                       'minecraft:patch_tall_grass_2',
                       'minecraft:patch_bush',
                       'minecraft:trees_plains',
                       'minecraft:flower_plains',
                       'minecraft:patch_grass_plain',
                       'minecraft:brown_mushroom_normal',
                       'minecraft:red_mushroom_normal',
                       'minecraft:patch_pumpkin',
                       'minecraft:patch_sugar_cane',
                       'minecraft:patch_firefly_bush_near_water'],
                      ['minecraft:freeze_top_layer']]},
 'snowy_plains': {'attributes': {'minecraft:gameplay/creature_world_gen_spawn_probability': 0.07},
                  'carvers': ['minecraft:cave', 'minecraft:cave_extra_underground', 'minecraft:canyon'],
                  'sky_color': '#7fa1ff',
                  'spawns': {'ambient': [{'count': 8, 'type': 'minecraft:bat', 'weight': 10}],
                             'creature': [{'count': {'max_inclusive': 3,
                                                     'min_inclusive': 2,
                                                     'type': 'minecraft:uniform'},
                                           'type': 'minecraft:rabbit',
                                           'weight': 10},
                                          {'count': {'max_inclusive': 2,
                                                     'min_inclusive': 1,
                                                     'type': 'minecraft:uniform'},
                                           'type': 'minecraft:polar_bear',
                                           'weight': 1}],
                             'monster': [{'count': 4, 'type': 'minecraft:spider', 'weight': 100},
                                         {'count': 4, 'type': 'minecraft:zombie', 'weight': 90},
                                         {'count': 1, 'type': 'minecraft:zombie_villager', 'weight': 5},
                                         {'count': 1, 'type': 'minecraft:zombie_horse', 'weight': 5},
                                         {'count': 4, 'type': 'minecraft:skeleton', 'weight': 20},
                                         {'count': 4, 'type': 'minecraft:creeper', 'weight': 100},
                                         {'count': 4, 'type': 'minecraft:slime', 'weight': 100},
                                         {'count': {'max_inclusive': 4,
                                                    'min_inclusive': 1,
                                                    'type': 'minecraft:uniform'},
                                          'type': 'minecraft:enderman',
                                          'weight': 10},
                                         {'count': 1, 'type': 'minecraft:witch', 'weight': 5},
                                         {'count': 4, 'type': 'minecraft:stray', 'weight': 80}],
                             'underground_water_creature': [{'count': {'max_inclusive': 6,
                                                                       'min_inclusive': 4,
                                                                       'type': 'minecraft:uniform'},
                                                             'type': 'minecraft:glow_squid',
                                                             'weight': 10}]},
                  'steps': [[],
                            ['minecraft:lake_lava_underground', 'minecraft:lake_lava_surface'],
                            ['minecraft:amethyst_geode'],
                            ['minecraft:monster_room', 'minecraft:monster_room_deep'],
                            [],
                            [],
                            ['minecraft:ore_dirt',
                             'minecraft:ore_gravel',
                             'minecraft:ore_granite_upper',
                             'minecraft:ore_granite_lower',
                             'minecraft:ore_diorite_upper',
                             'minecraft:ore_diorite_lower',
                             'minecraft:ore_andesite_upper',
                             'minecraft:ore_andesite_lower',
                             'minecraft:ore_tuff',
                             'minecraft:ore_coal_upper',
                             'minecraft:ore_coal_lower',
                             'minecraft:ore_iron_upper',
                             'minecraft:ore_iron_middle',
                             'minecraft:ore_iron_small',
                             'minecraft:ore_gold',
                             'minecraft:ore_gold_lower',
                             'minecraft:ore_redstone',
                             'minecraft:ore_redstone_lower',
                             'minecraft:ore_diamond',
                             'minecraft:ore_diamond_medium',
                             'minecraft:ore_diamond_large',
                             'minecraft:ore_diamond_buried',
                             'minecraft:ore_lapis',
                             'minecraft:ore_lapis_buried',
                             'minecraft:ore_copper',
                             'minecraft:underwater_magma',
                             'minecraft:disk_sand',
                             'minecraft:disk_clay',
                             'minecraft:disk_gravel'],
                            [],
                            ['minecraft:spring_water', 'minecraft:spring_lava'],
                            ['minecraft:glow_lichen',
                             'minecraft:trees_snowy',
                             'minecraft:flower_default',
                             'minecraft:patch_grass_badlands',
                             'minecraft:brown_mushroom_normal',
                             'minecraft:red_mushroom_normal',
                             'minecraft:patch_pumpkin',
                             'minecraft:patch_sugar_cane',
                             'minecraft:patch_firefly_bush_near_water'],
                            ['minecraft:freeze_top_layer']]},
 'snowy_taiga': {'carvers': ['minecraft:cave', 'minecraft:cave_extra_underground', 'minecraft:canyon'],
                 'sky_color': '#839eff',
                 'spawns': {'ambient': [{'count': 8, 'type': 'minecraft:bat', 'weight': 10}],
                            'creature': [{'count': 4, 'type': 'minecraft:sheep', 'weight': 12},
                                         {'count': 4, 'type': 'minecraft:pig', 'weight': 10},
                                         {'count': 4, 'type': 'minecraft:chicken', 'weight': 10},
                                         {'count': 4, 'type': 'minecraft:cow', 'weight': 8},
                                         {'count': 4, 'type': 'minecraft:wolf', 'weight': 8},
                                         {'count': {'max_inclusive': 3,
                                                    'min_inclusive': 2,
                                                    'type': 'minecraft:uniform'},
                                          'type': 'minecraft:rabbit',
                                          'weight': 4},
                                         {'count': {'max_inclusive': 4,
                                                    'min_inclusive': 2,
                                                    'type': 'minecraft:uniform'},
                                          'type': 'minecraft:fox',
                                          'weight': 8}],
                            'monster': [{'count': 4, 'type': 'minecraft:spider', 'weight': 100},
                                        {'count': 4, 'type': 'minecraft:zombie', 'weight': 95},
                                        {'count': 1, 'type': 'minecraft:zombie_villager', 'weight': 5},
                                        {'count': 4, 'type': 'minecraft:skeleton', 'weight': 100},
                                        {'count': 4, 'type': 'minecraft:creeper', 'weight': 100},
                                        {'count': 4, 'type': 'minecraft:slime', 'weight': 100},
                                        {'count': {'max_inclusive': 4,
                                                   'min_inclusive': 1,
                                                   'type': 'minecraft:uniform'},
                                         'type': 'minecraft:enderman',
                                         'weight': 10},
                                        {'count': 1, 'type': 'minecraft:witch', 'weight': 5}],
                            'underground_water_creature': [{'count': {'max_inclusive': 6,
                                                                      'min_inclusive': 4,
                                                                      'type': 'minecraft:uniform'},
                                                            'type': 'minecraft:glow_squid',
                                                            'weight': 10}]},
                 'steps': [[],
                           ['minecraft:lake_lava_underground', 'minecraft:lake_lava_surface'],
                           ['minecraft:amethyst_geode'],
                           ['minecraft:monster_room', 'minecraft:monster_room_deep'],
                           [],
                           [],
                           ['minecraft:ore_dirt',
                            'minecraft:ore_gravel',
                            'minecraft:ore_granite_upper',
                            'minecraft:ore_granite_lower',
                            'minecraft:ore_diorite_upper',
                            'minecraft:ore_diorite_lower',
                            'minecraft:ore_andesite_upper',
                            'minecraft:ore_andesite_lower',
                            'minecraft:ore_tuff',
                            'minecraft:ore_coal_upper',
                            'minecraft:ore_coal_lower',
                            'minecraft:ore_iron_upper',
                            'minecraft:ore_iron_middle',
                            'minecraft:ore_iron_small',
                            'minecraft:ore_gold',
                            'minecraft:ore_gold_lower',
                            'minecraft:ore_redstone',
                            'minecraft:ore_redstone_lower',
                            'minecraft:ore_diamond',
                            'minecraft:ore_diamond_medium',
                            'minecraft:ore_diamond_large',
                            'minecraft:ore_diamond_buried',
                            'minecraft:ore_lapis',
                            'minecraft:ore_lapis_buried',
                            'minecraft:ore_copper',
                            'minecraft:underwater_magma',
                            'minecraft:disk_sand',
                            'minecraft:disk_clay',
                            'minecraft:disk_gravel'],
                           [],
                           ['minecraft:spring_water', 'minecraft:spring_lava'],
                           ['minecraft:glow_lichen',
                            'minecraft:patch_large_fern',
                            'minecraft:trees_taiga',
                            'minecraft:flower_default',
                            'minecraft:patch_grass_taiga_2',
                            'minecraft:brown_mushroom_taiga',
                            'minecraft:red_mushroom_taiga',
                            'minecraft:patch_pumpkin',
                            'minecraft:patch_sugar_cane',
                            'minecraft:patch_firefly_bush_near_water',
                            'minecraft:patch_berry_rare'],
                           ['minecraft:freeze_top_layer']]},
 'taiga': {'carvers': ['minecraft:cave', 'minecraft:cave_extra_underground', 'minecraft:canyon'],
           'sky_color': '#7da3ff',
           'spawns': {'ambient': [{'count': 8, 'type': 'minecraft:bat', 'weight': 10}],
                      'creature': [{'count': 4, 'type': 'minecraft:sheep', 'weight': 12},
                                   {'count': 4, 'type': 'minecraft:pig', 'weight': 10},
                                   {'count': 4, 'type': 'minecraft:chicken', 'weight': 10},
                                   {'count': 4, 'type': 'minecraft:cow', 'weight': 8},
                                   {'count': 4, 'type': 'minecraft:wolf', 'weight': 8},
                                   {'count': {'max_inclusive': 3, 'min_inclusive': 2, 'type': 'minecraft:uniform'},
                                    'type': 'minecraft:rabbit',
                                    'weight': 4},
                                   {'count': {'max_inclusive': 4, 'min_inclusive': 2, 'type': 'minecraft:uniform'},
                                    'type': 'minecraft:fox',
                                    'weight': 8}],
                      'monster': [{'count': 4, 'type': 'minecraft:spider', 'weight': 100},
                                  {'count': 4, 'type': 'minecraft:zombie', 'weight': 95},
                                  {'count': 1, 'type': 'minecraft:zombie_villager', 'weight': 5},
                                  {'count': 4, 'type': 'minecraft:skeleton', 'weight': 100},
                                  {'count': 4, 'type': 'minecraft:creeper', 'weight': 100},
                                  {'count': 4, 'type': 'minecraft:slime', 'weight': 100},
                                  {'count': {'max_inclusive': 4, 'min_inclusive': 1, 'type': 'minecraft:uniform'},
                                   'type': 'minecraft:enderman',
                                   'weight': 10},
                                  {'count': 1, 'type': 'minecraft:witch', 'weight': 5}],
                      'underground_water_creature': [{'count': {'max_inclusive': 6,
                                                                'min_inclusive': 4,
                                                                'type': 'minecraft:uniform'},
                                                      'type': 'minecraft:glow_squid',
                                                      'weight': 10}]},
           'steps': [[],
                     ['minecraft:lake_lava_underground', 'minecraft:lake_lava_surface'],
                     ['minecraft:amethyst_geode'],
                     ['minecraft:monster_room', 'minecraft:monster_room_deep'],
                     [],
                     [],
                     ['minecraft:ore_dirt',
                      'minecraft:ore_gravel',
                      'minecraft:ore_granite_upper',
                      'minecraft:ore_granite_lower',
                      'minecraft:ore_diorite_upper',
                      'minecraft:ore_diorite_lower',
                      'minecraft:ore_andesite_upper',
                      'minecraft:ore_andesite_lower',
                      'minecraft:ore_tuff',
                      'minecraft:ore_coal_upper',
                      'minecraft:ore_coal_lower',
                      'minecraft:ore_iron_upper',
                      'minecraft:ore_iron_middle',
                      'minecraft:ore_iron_small',
                      'minecraft:ore_gold',
                      'minecraft:ore_gold_lower',
                      'minecraft:ore_redstone',
                      'minecraft:ore_redstone_lower',
                      'minecraft:ore_diamond',
                      'minecraft:ore_diamond_medium',
                      'minecraft:ore_diamond_large',
                      'minecraft:ore_diamond_buried',
                      'minecraft:ore_lapis',
                      'minecraft:ore_lapis_buried',
                      'minecraft:ore_copper',
                      'minecraft:underwater_magma',
                      'minecraft:disk_sand',
                      'minecraft:disk_clay',
                      'minecraft:disk_gravel'],
                     [],
                     ['minecraft:spring_water', 'minecraft:spring_lava'],
                     ['minecraft:glow_lichen',
                      'minecraft:patch_large_fern',
                      'minecraft:trees_taiga',
                      'minecraft:flower_default',
                      'minecraft:patch_grass_taiga_2',
                      'minecraft:brown_mushroom_taiga',
                      'minecraft:red_mushroom_taiga',
                      'minecraft:patch_pumpkin',
                      'minecraft:patch_sugar_cane',
                      'minecraft:patch_firefly_bush_near_water',
                      'minecraft:patch_berry_common'],
                     ['minecraft:freeze_top_layer']]}}
